name: 'Resources'

on: [workflow_dispatch]

permissions: write-all
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "ap-southeast-1"    
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Creating the file name
      run: |
        echo -n bucket=\"do-not-delete-awsgoat-state-files->temp
        aws sts get-caller-identity --query Account --output text >> temp
        sed -i.bak 's/^..*$/&"/' temp
      continue-on-error: true
    
    - name: Backend_file
      run: |
        cat > conf.tf << EOF
        terraform {
          backend "s3" {
            region = "us-west-2"
            key = "terraform.tfstate"
        EOF
        cat temp >> conf.tf
        echo } >>conf.tf
        echo } >>conf.tf
    
    - name: Terraform Init
      run: terraform init 
          
    - name: Terraform Destroy
      run: terraform destroy -auto-approve -input=false
      
