name: 'Resources'

on: [workflow_dispatch]

permissions: write-all
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "ap-southeast-1"    
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Creating the file name
      run: |
        echo -n THINGS=do-not-delete-awsgoat-state-files->file
        echo -n bucket=\"do-not-delete-awsgoat-state-files->temp
        aws sts get-caller-identity --query Account --output text >> file
        aws sts get-caller-identity --query Account --output text >> temp
        export $(cat file) 
        sed -i.bak 's/^..*$/&"/' temp
        aws s3api create-bucket --bucket $THINGS --region eu-west-1
      continue-on-error: true
    
    - name: Backend_file
      run: |
        cat > conf.tf << EOF
        terraform {
          backend "s3" {
            region = "us-west-2"
            key = "terraform.tfstate"
        EOF
        cat temp >> conf.tf
        #echo -n \" >>conf.tf
        echo } >>conf.tf
        echo } >>conf.tf

    - name: Terraform Init
      run: |
        terraform init 
        ls -al
    
    - name: Terraform Plan
      run: | 
        terraform plan -input=false
      continue-on-error: true
      
    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: "exit 1"
    
    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
